on:
  workflow_call:
    inputs:
      ws:
        required: true
        type: string
      org:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  Terraform-Init:
    runs-on: ubuntu-latest
    steps:
      - name: TF State Backend
        run: |
          sed -i 's/##TERRAFORM-WS##/${{ inputs.ws}}/' main.tf
          sed -i 's/##TERRAFORM-ORG##/${{ inputs.org }}/' main.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
