repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.4.1
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
        exclude: ^examples|.terraform/
      - id: tflint
      - id: phony-targets
      - id: terradoc-validate
      - id: terradoc-fmt
      - id: terradoc-generate
